import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBarLateral from "./component/NavBarLateral";
import { ConvenioProvider } from "./context/convenio";
import { Toaster } from "sonner";
import { EspecialidadeProvider } from "./context/especialidade";
import { DisponibilidadeProvider } from "./context/disponibilidade";
import { AgendamentoProvider } from "./context/AgendamentoContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AgendamentoProvider>
          <DisponibilidadeProvider>
            <ConvenioProvider>
              <EspecialidadeProvider>
                <NavBarLateral>{children}</NavBarLateral>
                <Toaster position="top-right" />
              </EspecialidadeProvider>
            </ConvenioProvider>
          </DisponibilidadeProvider>
        </AgendamentoProvider>
      </body>
    </html>
  );
}
